const frases =
[
"✨ Dios te ama, aunque a veces lo olvides.",
"🙏 Confía en el Señor, incluso cuando no veas el camino.",
"💛 La fe no hace las cosas fáciles, las hace posibles.",
"📿 María, Madre de Dios, ruega por nosotros.",
"🌿 Jesús es la luz que nunca se apaga.",
"🕊️ La oración es el puente que une tu corazón con el cielo.",
"🔥 Donde hay fe, hay milagros.",
"💫 No temas, Cristo camina contigo.",
"💐 Ora con amor, y el amor te responderá.",
"🌸 Todo lo que sucede tiene un propósito en los planes de Dios.",
"🌞 El Señor ilumina tus días con su amor.",
"⛪ La fe mueve montañas y corazones.",
"🌈 Confía, que después de la tormenta viene la bendición.",
"💝 Dios escucha hasta el susurro de tu corazón.",
"🕯️ La oración constante transforma la vida.",
"💌 El amor de Cristo no tiene límites.",
"🌹 María cuida de ti con ternura infinita.",
"🙏 La paciencia es un fruto de la fe.",
"💎 Cada día es un regalo de Dios.",
"🌟 Cree, que Dios tiene un plan perfecto para ti.",
"💫 La esperanza es luz en la oscuridad.",
"🔥 Dios convierte tu debilidad en fortaleza.",
"🕊️ Vive en paz y deja que Dios guíe tu alma.",
"🌿 La fe es el ancla del corazón.",
"💛 Confía en la voluntad divina.",
"📿 La oración es la llave que abre milagros.",
"🌸 Dios nunca abandona a sus hijos.",
"💐 Cada amanecer es un mensaje de amor divino.",
"✨ Jesús transforma tu tristeza en alegría.",
"🙏 La fe te da alas para volar sobre el miedo.",
"💎 Dios escucha tus suspiros más profundos.",
"🌟 La luz de Cristo ilumina los senderos difíciles.",
"🔥 Donde hay oración, hay paz.",
"🕯️ El amor de Dios calma cualquier tormenta.",
"🌞 Confía en que lo mejor está por venir.",
"⛪ María acompaña cada paso de tu vida.",
"🌈 Dios escribe historias hermosas en tu corazón.",
"💌 Ama con fe y recibirás bendiciones.",
"💐 Cada acción de bondad es un acto de Dios.",
"💫 La oración transforma lo imposible en posible.",
"💛 Dios te fortalece cuando te sientes débil.",
"🌿 La esperanza en el Señor nunca falla.",
"🕊️ Vive con fe, incluso en la oscuridad.",
"🔥 Cristo es tu refugio en tiempos difíciles.",
"✨ Dios conoce tu corazón mejor que nadie.",
"🙏 La gratitud abre las puertas del cielo.",
"💎 Confía y verás milagros en tu vida.",
"🌟 La paz de Dios llena tu alma.",
"💐 La fe es la brújula que guía tu vida.",
"🌸 Dios está contigo en cada momento.",
"🕯️ La oración constante trae serenidad.",
"💌 Ama como Jesús nos enseñó.",
"🌞 La luz de Dios disipa toda sombra.",
"⛪ María protege a quienes confían en ella.",
"💛 La fe te da fuerza para seguir adelante.",
"🔥 Cada desafío es una oportunidad de acercarte a Dios.",
"💫 No pierdas la esperanza, Dios está contigo.",
"🌿 La oración diaria alimenta el espíritu.",
"🕊️ Cristo es el faro en la tormenta.",
"💐 Dios multiplica tu amor y bondad.",
"✨ Confía en los planes perfectos de Dios.",
"🙏 La paciencia fortalece la fe.",
"💎 Cada día es un regalo divino.",
"🌟 Dios escucha cada palabra de tu corazón.",
"💌 Ama con el corazón lleno de fe.",
"🌸 La oración transforma la tristeza en alegría.",
"🕯️ Dios es refugio seguro para tu alma.",
"🔥 Donde hay fe, Dios obra milagros.",
"💛 La luz de Cristo guía tus pasos.",
"🌿 Vive con esperanza y amor en Dios.",
"💫 La fe hace que todo sea posible.",
"💐 Dios conoce tus necesidades y deseos.",
"🌞 Cristo es la luz que ilumina tu camino.",
"⛪ María intercede por ti ante Dios.",
"🌈 Confía en que cada prueba tiene un propósito.",
"✨ Dios fortalece a quienes le buscan con corazón sincero.",
"🕊️ La oración es un puente hacia la paz interior.",
"💎 Cada sonrisa es un regalo del Señor.",
"🔥 Dios transforma las pruebas en bendiciones.",
"💛 Vive en fe y esperanza cada día.",
"💐 Ama a los demás como Dios te ama.",
"💫 Cristo renueva tu espíritu con su amor.",
"🌟 La paciencia y la oración traen bendiciones.",
"🌿 Dios siempre camina a tu lado.",
"🕯️ La fe en Jesús nunca decepciona.",
"💌 Cada acto de amor refleja la luz divina.",
"🌸 Confía y deja que Dios haga su obra.",
"💛 Dios escucha tu corazón y responde con amor.",
"✨ La oración diaria fortalece el alma.",
"🔥 Donde hay amor, hay presencia de Dios.",
"💐 Vive con gratitud y esperanza.",
"🌞 Cristo es refugio y consuelo.",
"⛪ María guía tu camino con ternura.",
"🌈 Dios convierte lágrimas en sonrisas.",
"💫 La fe es la fuerza que vence el miedo.",
"🕊️ Confía en Dios y descansa en su paz.",
"💎 La oración constante abre puertas divinas.",
"💌 Ama con el corazón lleno de luz.",
"🌿 Cada día es una oportunidad para acercarte a Dios.",
"🔥 Cristo fortalece tus debilidades.",
"🌟 Dios transforma los obstáculos en bendiciones.",
"💐 Vive con amor y esperanza en el Señor.",
"💛 La paciencia y la fe producen frutos eternos.",
"🕯️ La oración trae calma y serenidad.",
"✨ Dios te guía aunque no lo veas.",
"🌸 Cada momento puede ser un milagro.",
"💌 Ama sin miedo y Dios te acompañará.",
"🌞 La luz divina siempre ilumina tu camino.",
"💫 La fe transforma lo imposible en posible.",
"🔥 Cristo llena tu corazón de paz.",
"🕊️ Vive en armonía con el amor de Dios.",
"💎 Cada acto de bondad refleja su luz.",
"💐 Dios conoce cada deseo de tu corazón.",
"⛪ María intercede por tu bienestar y paz.",
"🌈 La esperanza en Dios nunca se desvanece.",
"💛 La oración abre el corazón a los milagros.",
"✨ Cristo camina contigo en cada paso.",
"💌 Vive con gratitud y confianza.",
"🌸 La fe y la paciencia traen recompensas divinas.",
"🕯️ Dios escucha incluso los suspiros del alma.",
"🔥 Donde hay fe, Dios obra maravillas.",
"💫 Cada día es una oportunidad de amar como Jesús.",
"💐 La oración transforma la vida de quienes creen.",
"🌟 Confía en Dios y verás su obra en ti.",
"💛 Ama como Cristo nos enseñó.",
"🕊️ La paz de Dios llena tu corazón.",
"🌿 Cada prueba puede acercarte más a Dios.",
"💎 La esperanza renace en la oración constante.",
"✨ Vive con fe, esperanza y amor.",
"🌞 Dios ilumina tu camino aun en la oscuridad.",
"💌 Ama y ayuda a los demás como Dios te guía.",
"🔥 La oración es fuerza y protección.",
"💫 Confía en el Señor y todo será posible.",
"💐 Cristo está contigo en cada momento.",
"🌸 La paciencia y la fe producen frutos hermosos.",
"🕯️ Dios nunca abandona a sus hijos.",
"💛 La luz de Cristo brilla en tu corazón.",
"🌟 Cada oración trae paz y esperanza.",
"🌿 Dios fortalece a los que confían en Él.",
"💌 Ama con alegría y fe en tu corazón.",
"✨ Cristo transforma tristeza en felicidad.",
"🔥 La oración diaria trae bendiciones infinitas.",
"💐 Vive con fe y confianza en Dios.",
"🕊️ Cada acto de amor refleja la presencia de Cristo.",
"💎 La esperanza en Dios renueva el alma.",
"🌞 Confía en la guía divina en tu vida.",
"⛪ María protege y cuida a quienes le aman.",
"💫 Dios convierte lágrimas en alegrías.",
"🌸 La fe abre las puertas a los milagros.",
"💛 La oración fortalece el corazón.",
"💌 Ama con el corazón lleno de luz divina.",
"🕯️ Dios escucha cada pensamiento y sentimiento.",
"🔥 Cristo es refugio en tiempos difíciles.",
"🌿 Vive con gratitud y fe cada día.",
"💫 La paciencia y la oración traen bendiciones.",
"💐 Confía en que Dios tiene un plan perfecto.",
"✨ Cada amanecer es un regalo de Dios.",
"🕊️ La fe en Jesús da esperanza y fuerza.",
"💎 Ama con humildad y gratitud.",
"🌟 Dios obra milagros en quienes creen.",
"💛 La oración es un acto de amor.",
"🌸 Cristo renueva la esperanza en tu vida.",
"💌 Vive con fe, amor y esperanza.",
"🔥 Dios guía tus pasos aunque no lo veas.",
"💫 La fe transforma el miedo en valentía.",
"🕯️ Ama y ora, y Dios responderá.",
"🌿 Cada día es una oportunidad de acercarte a Cristo.",
"💐 Dios conoce cada pensamiento y sentimiento.",
"✨ La oración constante trae paz y fortaleza.",
"🕊️ Vive con fe y deja que Dios guíe tu corazón.",
"💛 La esperanza en Dios nunca falla.",
"🌞 Cristo ilumina los caminos difíciles.",
"💎 Cada acto de bondad es un reflejo de Dios.",
"🌟 La paciencia y la oración fortalecen el espíritu.",
"💌 Ama sin medida y confía en el Señor.",
"🌸 La fe es la fuerza que mueve montañas.",
"🔥 Dios transforma los retos en oportunidades.",
"💫 Cada día es una bendición divina.",
"🕯️ Confía y deja que Cristo obre en tu vida.",
"💐 La luz de Dios brilla aun en la oscuridad.",
"✨ La oración es el puente hacia la paz interior.",
"💛 Cristo camina contigo siempre.",
"🌿 La paciencia y la esperanza dan frutos eternos.",
"💎 Ama como Dios nos ama.",
"🕊️ Cada prueba es una oportunidad de crecer en fe.",
"🌞 Confía en la voluntad divina.",
"💫 Dios fortalece tu espíritu en cada desafío.",
"💌 Vive con gratitud y amor.",
"🌸 Cristo renueva tu corazón y mente.",
"🔥 La fe abre caminos donde parece no haber ninguno.",
"💐 La oración trae serenidad y fortaleza.",
"✨ Ama y confía, y Dios hará maravillas.",
"🕯️ Cada día es un regalo para acercarte a Él.",
"💛 Dios está contigo en cada momento de tu vida.",
"🌟 La esperanza nunca se pierde con fe y oración.",
"💎 La luz de Cristo guía todos tus pasos.",
"🌿 Ama con el corazón lleno de fe.",
"💫 La oración diaria transforma vidas.",
"💌 Confía en los planes de Dios para ti.",
"🌸 Cristo es la fuente de paz y amor.",
"🔥 Cada acto de bondad refleja la presencia de Dios.",
"🕊️ La paciencia y la fe traen bendiciones infinitas."
];
